Create first game
PZalles/JS-9.7 pull request #1
Opened 2018-02-09 14:10 UTC by PZalles

2018-02-10 21:26 UTC, matwjablonski requested changes

2018-02-10 21:26 UTC, matwjablonski commented on js/scripts.js
> +function playerPick(playerPick) {
what will do this function? you have duplicated names of functions ;)

2018-02-10 21:26 UTC, matwjablonski commented on js/scripts.js
> +    if (playerPick == computerPick) {
always when you want to compare to variables you should compare also type of this variables

2018-02-10 21:26 UTC, matwjablonski commented on js/scripts.js
> +function playerPick(playerPick) {
third time?

2018-02-10 21:26 UTC, matwjablonski commented on js/scripts.js
> +	setTimeout(checkGameEnd, 0);
why timeout?

2018-02-11 18:33 UTC, PZalles commented on js/scripts.js
> +function playerPick(playerPick) {
It display player pick in console. Deleted it.

2018-02-12 07:08 UTC, matwjablonski approved these changes

2018-02-12 11:18 UTC, merged